# Site Settings
locale                   : "en-US"
title                    : "Groco Shop"
title_separator          : "-"
name                     : &name "Nargiz"
description              : &description "personal description"
url                      : https://nargizkani.github.io/grocery-store/ # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "home" # the subpath of your site, e.g. "/home"
